// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Core.Entities
{
    public partial class Operation
    {
        public string TransactionId { get; set; }
        public string AccountId { get; set; }
        public decimal OperationAmount { get; set; }
        [JsonIgnore]
        public virtual Account Account { get; set; }
    }
}