// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Infrastructure.Data
{
    public partial class OpearationsLog
    {
        public int Logid { get; set; }
        public string AccountId { get; set; }
        public DateTime OperationDateTime { get; set; }
        public string IpAddress { get; set; }
        public string Request { get; set; }
        public string Response { get; set; }
        public byte Status { get; set; }

        public virtual Acoount Account { get; set; }
    }
}