// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Infrastructure.Data
{
    public partial class Operation
    {
        public string TransactionId { get; set; }
        public string AccountId { get; set; }
        public decimal OperationAmount { get; set; }
        public byte OperationType { get; set; }

        public virtual Acoount Account { get; set; }
    }
}